hw1 PR
nikitakosh/TinkJavaCourse pull request #1
Opened 2023-10-10 18:23 UTC by nikitakosh

2023-10-13 13:21 UTC, yrlvdplsh requested changes

2023-10-13 13:21 UTC, yrlvdplsh commented on src/main/java/edu/hw1/Task6.java
> +    private static final int BASE = 6174;
BASE странное имечко для этой переменной, давай чуть более осмысленно назовем

2023-10-13 13:21 UTC, yrlvdplsh commented on src/test/java/edu/hw1/Task1Test.java
> +    public void minutesToSecondsTestInputMinutesAndSeconds(){
Давай добавим еще тесткейс когда в минутах больше 2 разрядов и объединим такие тесты с помощью @ParameterizedTest. А также добавим во все тесты те случаи, которые явно указаны в задаче

2023-10-13 15:37 UTC, nikitakosh commented on src/main/java/edu/hw1/Task6.java
> +    private static final int BASE = 6174;
исправил на KAPREKAR_CONSTANT

2023-10-13 15:40 UTC, nikitakosh commented on src/test/java/edu/hw1/Task1Test.java
> +    public void minutesToSecondsTestInputMinutesAndSeconds(){
Я добавил @ParameterizedTest c двумя аргументами. Ещё увидел недочёт и сделал проверку строки на null. При вводе null теперь выбрасывается NullPointerException.  И добавил тест на ввод null.

2023-10-15 13:30 UTC, yrlvdplsh commented on src/test/java/edu/hw1/Task1Test.java
> +    public void minutesToSecondsTestInputMinutesAndSeconds(){
Здорово, но ParameterizedTest стоит размножить на все тесты с одинаковой логикой проверки. В будущих дз учти это пж.

2023-10-15 15:14 UTC, merged